config/routes.rb
Rails.application.routes.draw do

  resources :games
  root 'games#index'

  get '/memory', to: 'games#memory'
  get '/calc', to: 'games#calc'
  get '/puzzle', to: 'games#puzzle'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="container">
  <h1>Games</h1>
  <ul>
    <li><%= link_to 'Numbers Memory', memory_path %></li>
    <li><%= link_to 'Calculus', calc_path %></li>
    <li><%= link_to 'Hidden puzzle', puzzle_path %></li>
  </ul>
</div>

app/views/games/memory.html.erb
<div class="container">
  <h1 class="title">Numbers Memory Game</h1>
  <div class="game-wrapper">
    <a href="#" class="js-start btn">Start Game</a>
    <div class="numbers-container">
      <div class="numbers-container__number">
        <p class="js-randNumber"></p>
        <div class="progress-bar"><span></span></div>
      </div>
      <div class="numbers-container__input">
        <input id="player-input" type="text" name="player-number" class="input input--number" autofocus>
        <a href="#" class="js-submit-number btn">Submeter</a>
      </div>
    </div>
  </div>

  <div class="game-divider">
    <p>Resultado: <span class="js-result"></span></p>

    <div id="game-win" class="game-divider__actions">
      <a href="#" class="js-next-level btn">Próximo Nível</a>
      <%= link_to 'Voltar', memory_path, :class => 'btn' %>
    </div>

    <div id="game-lose" class="game-divider__actions">
      <a href="#" class="js-repeat-level btn">Repetir</a>
      <%= link_to 'Voltar', memory_path, :class => 'btn' %>
    </div>
  </div>

  <div id="feedback-modal" class="feedback-modal">
    <p class="js-feedback"></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jogos</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<header>
  <ul class="navbar">
    <li class="navbar__item">Logic</li>
    <li class="navbar__item">Brain Games</li>
    <li class="navbar__item">Action and fun</li>
  </ul>
</header>